T31123 install msgs (DONTMERGE, Review Only)
endlessm/clubhouse pull request #1214
Opened 2020-11-20 01:21 UTC by bkarnow

Extending the autoinstall flow to allow non-generic messages.
To do this I reworked `step_app_not_installed` - Now searches first for a 'group' install message under `__app_common_install_name__`, then a `NOTINSTALLED` string in the quest's strings, then finally falls back on the generic message.
The Blender quests have been migrated over to this new flow - let me know what you think, if this works I'll migrate all the other quests over and add them to this PR before submitting.

https://phabricator.endlessm.com/T31123

2020-11-20 22:42 UTC, bkarnow commented
I think having this as a draft is better for "don't merge" PRs

2020-11-27 14:07 UTC, erikos requested changes

2020-11-27 14:07 UTC, erikos commented on data/quests_strings/noquest.csv
> +NOQUEST_AUTOINSTALL,"OK, I'll try to start the App install, this shouldn't take too long!",daemon,,,
It is a bit unclear what happens here. In EOS GNOME Software is started (on the detail page) but the dialogue suggests that the app might be installed automatically without further intervention. But the user still has to start the installation.

2020-11-27 14:07 UTC, erikos commented on eosclubhouse/libquest.py
> +            if has_install_msg:
Could be reduced to a one liner.  
`install_msg = 'NOTINSTALLED' if has_install_msg else 'NOQUEST_NOTINSTALLED_GENERIC'`

2020-11-27 14:52 UTC, erikos commented on eosclubhouse/libquest.py
>              self.wait_for_app_install(self.app, confirm=True, repo=self.__app_repository__)
We can automatically install the app here. Then we should pass `confirm=False`. That would match better the corresponding current dialogue.

One thing I noticed is that the installation process can not be cancelled in the app center once initiated from the quest.

2020-11-27 14:54 UTC, erikos commented on data/quests_strings/noquest.csv
> +NOQUEST_NOTINSTALLED_GENERIC,Uh-oh! It looks like the App this quest needs isn't installed! Would you like me to help you install it?,daemon,,,
We need to phrase it more clearly. When we install the app automatically, this dialogue should state it clearly. For example: Uh-oh! It looks like the App this quest needs isn't installed! Would you like me to install it for you?

2020-11-27 15:29 UTC, merged